### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by jmckenn7** [ksu-is/Text-based-RPG-#2]
- [x] Find tutorial/example code
- [x] Test example code
- [x] Decide on game style
- [x] Design blueprint of game
- [x] Design Player system
- [x] Design Title Screen
- [x] Decide on map style and size
- [x] Decide on map layout
- [x] Design map
- [ ] Design Interactivity 
- [ ] Decide what user inputs to gather and where
- [ ] Design game introduction and title screen
- [ ] Test code
- [ ] Debug 1
- [ ] Test code after 1st debug 
- [ ] Bug Free code
- [ ] Ensure everything is working properly
- [ ] Fix any issues
- [ ] Run code again and ensure it is working
- [ ] Create project image
- [ ] Create project presentation
- [ ] Submit project
